<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.Hcl.DirectCommerce.Modifyorder.Verify_Modify_order_by_adding_new_items_R1" tests="2" time="0.000" ignored="0" failures="0" timestamp="06 Jan 2022 06:05:29 GMT" skipped="1" hostname="IN2-1025604LT" errors="1">
  <testcase name="R1_OA" time="0.000" classname="com.Hcl.DirectCommerce.Modifyorder.Verify_Modify_order_by_adding_new_items_R1">
    <skipped/>
  </testcase> <!-- R1_OA -->
  <testcase name="returnOrder1" time="0.000" classname="com.Hcl.DirectCommerce.Modifyorder.Verify_Modify_order_by_adding_new_items_R1">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.Hcl.DirectCommerce.testBase.TestBase.logExtentReport(TestBase.java:195)
	at com.Hcl.DirectCommerce.ApiMethod.reusableAPIMethodsPage.retrurnordernumber(reusableAPIMethodsPage.java:150)
	at com.Hcl.DirectCommerce.Modifyorder.Verify_Modify_order_by_adding_new_items_R1.returnOrder1(Verify_Modify_order_by_adding_new_items_R1.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- returnOrder1 -->
</testsuite> <!-- com.Hcl.DirectCommerce.Modifyorder.Verify_Modify_order_by_adding_new_items_R1 -->
